version: 2
updates:
  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
    groups:
      npm-backend:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /frontend/corvale
    schedule:
      interval: weekly
    groups:
      npm-frontend:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: weekly
    groups:
      npm-docs:
        patterns:
          - '*'

  - package-ecosystem: cargo
    directory: /frontend/corvale/src-tauri
    schedule:
      interval: weekly
    groups:
      cargo-desktop:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
