import { Model, Types } from 'mongoose'

import Transaction from '../models/Transaction'
import Account from '../models/Account'
import Category from '../models/Category'
import Receipt from '../models/Receipt'
import Budget from '../models/Budget'
import SavingsGoal from '../models/SavingsGoal'
import SavingsGoalContribution from '../models/SavingsGoalContribution'
import RecurringRule from '../models/RecurringRule'
import Tag from '../models/Tag'
import CategorizationRule from '../models/CategorizationRule'
import TransactionTemplate from '../models/TransactionTemplate'
import Notification from '../models/Notification'
import Saver from '../models/Saver'
import Pushover from '../models/Pushover'
import ReconciliationSession from '../models/ReconciliationSession'
import SavedReport from '../models/SavedReport'
import Income from '../models/Income'
import Expense from '../models/Expense'
import Workspace, { IWorkspace } from '../models/Workspace'
import User from '../models/User'
import { CustomError } from './customError'
import { ERROR_MESSAGES } from './errorMessages'
import { revokeAllRefreshTokensForUser } from './refreshTokenService'
import { deleteReceiptFile } from './receiptUtils'
import { deleteReceiptObject, isObjectStorageConfigured, receiptObjectKey } from './receiptStorage'
import { SOFT_DELETE_BYPASS } from './softDelete'
import { RLS_BYPASS } from './rowLevelSecurity'
import { createNotificationIfNew } from './notificationUtils'

const BYPASS_SOFT_DELETE = { [SOFT_DELETE_BYPASS]: true }

/**
 * Sentinel `userId` used to sever a departing member's identity from a workspace record that is
 * being retained for the workspace's other members (see `deleteUserAccountCascade` below).
 *
 * Why a fixed sentinel rather than making `userId` nullable: every workspace-capable schema
 * declares `userId: { required: true }`, and every other consumer in the codebase
 * (`validateResourceAccess`, `computeBudgetSpentMinor`'s scope filter, `assertWorkspaceMembership`
 * call sites, etc.) treats `resource.userId` as a guaranteed `ObjectId`. Relaxing that to
 * `| null` for one narrow case would ripple through all of them for no benefit. A fixed all-zero
 * ObjectId is never generated by Mongo for a real document (real ids embed a timestamp + machine
 * + process + counter component - see the Mongo ObjectId spec), and no `User` document is ever
 * created with this `_id`, so it can never resolve to - or be confused with - a real account.
 * `createdByRemovedUser` is the explicit, queryable signal that a record's `userId` is this
 * sentinel rather than an accident of one being reused; the sentinel itself is only the
 * mechanical value that satisfies `required: true`.
 *
 * Deliberately NOT reassigned to another real member's id - misattributing a departed member's
 * transactions to whoever happens to still be in the workspace would be worse than the bug this
 * fixes.
 */
export const REMOVED_MEMBER_USER_ID = new Types.ObjectId('000000000000000000000000')

interface WorkspaceCapableDoc {
    _id: Types.ObjectId
    userId: Types.ObjectId
    workspaceId?: Types.ObjectId | null
}

interface WorkspaceCapableModelConfig {
    model: Model<WorkspaceCapableDoc>
    /** Whether this model also runs the soft-delete plugin (needs SOFT_DELETE_BYPASS to reach
     *  tombstoned rows too, so a hard-delete/anonymise pass here is genuinely complete). */
    softDelete: boolean
}

/**
 * Every model that declares `applyRowLevelSecurity(schema, { supportsWorkspace: true })` - i.e.
 * can carry a non-null `workspaceId` and therefore be shared with other workspace members.
 * `SavingsGoalContribution`, `Tag`, `CategorizationRule`, `TransactionTemplate`, `Saver`,
 * `Pushover`, `Notification`, `Income`, `Expense` and personal `Category` rows have no
 * `workspaceId` field at all - they stay unconditionally `userId`-scoped and hard-deleted below,
 * unchanged from the old behaviour.
 */
const WORKSPACE_CAPABLE_MODELS: WorkspaceCapableModelConfig[] = [
    { model: Transaction as unknown as Model<WorkspaceCapableDoc>, softDelete: true },
    { model: Account as unknown as Model<WorkspaceCapableDoc>, softDelete: false },
    { model: Budget as unknown as Model<WorkspaceCapableDoc>, softDelete: false },
    { model: SavingsGoal as unknown as Model<WorkspaceCapableDoc>, softDelete: false },
    { model: RecurringRule as unknown as Model<WorkspaceCapableDoc>, softDelete: false },
    { model: ReconciliationSession as unknown as Model<WorkspaceCapableDoc>, softDelete: false },
    { model: SavedReport as unknown as Model<WorkspaceCapableDoc>, softDelete: true },
]

/**
 * Blocks account deletion (409) when the caller is the sole owner of a workspace that still
 * has other members - ownership must be transferred, or the workspace deleted, first, so
 * deleting one account can never require picking a new owner mid-cascade.
 */
export const assertAccountDeletionAllowed = async (userId: string): Promise<void> => {
    const ownedWorkspaces = await Workspace.find({ ownerId: userId })
    const hasOtherMembers = ownedWorkspaces.some((workspace) => workspace.members.length > 1)

    if (hasOtherMembers) {
        throw new CustomError(ERROR_MESSAGES.WORKSPACE.SOLE_OWNER_HAS_MEMBERS, 409)
    }
}

interface WorkspaceDepartureImpact {
    /** Workspaces this user is a member of that will still have other members once they leave -
     *  their workspace records here are retained (creator link severed), not deleted. */
    retainedWorkspaceIds: Types.ObjectId[]
    /** Workspaces this user is a member of that will have nobody left once they leave (only
     *  reachable when they are the sole owner - see `assertAccountDeletionAllowed`) - every
     *  record under these, and the workspace itself, is hard-deleted. */
    emptiedWorkspaceIds: Types.ObjectId[]
    /** The full workspace documents behind `retainedWorkspaceIds`, kept around so the caller
     *  doesn't have to re-fetch them to notify remaining members or report workspace names. */
    retainedWorkspaces: IWorkspace[]
}

const computeWorkspaceDepartureImpact = async (userId: string): Promise<WorkspaceDepartureImpact> => {
    const memberWorkspaces = await Workspace.find({ 'members.userId': userId })

    const retainedWorkspaceIds: Types.ObjectId[] = []
    const emptiedWorkspaceIds: Types.ObjectId[] = []
    const retainedWorkspaces: IWorkspace[] = []

    for (const workspace of memberWorkspaces) {
        const remainingMemberCount = workspace.members.filter(
            (member) => member.userId.toString() !== userId
        ).length

        if (remainingMemberCount > 0) {
            retainedWorkspaceIds.push(workspace._id)
            retainedWorkspaces.push(workspace)
        } else {
            emptiedWorkspaceIds.push(workspace._id)
        }
    }

    return { retainedWorkspaceIds, emptiedWorkspaceIds, retainedWorkspaces }
}

export interface AccountDeletionImpact {
    /** Total live records this user created, across every workspace-capable collection, that
     *  will be retained (anonymised) rather than deleted - i.e. what "belongs" to someone else's
     *  workspace and would otherwise silently vanish out from under them. */
    retainedRecordCount: number
    affectedWorkspaces: { workspaceId: string; name: string }[]
}

/**
 * Preview for `GET /auth/account/deletion-impact` (Part 1 of the account-deletion redesign) -
 * read-only, so the user can see what will happen before they type their password and commit.
 * Mirrors `deleteUserAccountCascade`'s retain/delete split without mutating anything: only
 * `retainedWorkspaceIds` records are counted here, because `emptiedWorkspaceIds` records are
 * hard-deleted (same as a personal record), not retained, and shouldn't be reported as "will stay
 * in the workspace".
 */
export const computeAccountDeletionImpact = async (userId: string): Promise<AccountDeletionImpact> => {
    const { retainedWorkspaceIds } = await computeWorkspaceDepartureImpact(userId)

    if (retainedWorkspaceIds.length === 0) {
        return { retainedRecordCount: 0, affectedWorkspaces: [] }
    }

    const countsByWorkspace = new Map<string, number>()
    let retainedRecordCount = 0

    for (const { model } of WORKSPACE_CAPABLE_MODELS) {
        const rows = await model.aggregate([
            {
                $match: {
                    userId: new Types.ObjectId(userId),
                    workspaceId: { $in: retainedWorkspaceIds },
                },
            },
            { $group: { _id: '$workspaceId', count: { $sum: 1 } } },
        ])

        for (const row of rows as { _id: Types.ObjectId; count: number }[]) {
            const key = row._id.toString()
            countsByWorkspace.set(key, (countsByWorkspace.get(key) ?? 0) + row.count)
            retainedRecordCount += row.count
        }
    }

    const affectedWorkspaceIds = [...countsByWorkspace.keys()].filter(
        (id) => (countsByWorkspace.get(id) ?? 0) > 0
    )
    const workspaces =
        affectedWorkspaceIds.length > 0
            ? await Workspace.find({ _id: { $in: affectedWorkspaceIds } }).select('name')
            : []

    return {
        retainedRecordCount,
        affectedWorkspaces: workspaces.map((workspace) => ({
            workspaceId: workspace._id.toString(),
            name: workspace.name,
        })),
    }
}

const deleteUserReceipts = async (userId: string): Promise<Types.ObjectId[]> => {
    const receipts = await Receipt.find({ userId })
    const receiptIds = receipts.map((receipt) => receipt._id)

    for (const receipt of receipts) {
        if (isObjectStorageConfigured()) {
            await deleteReceiptObject(receiptObjectKey(userId, receipt.storedFilename))
        } else {
            deleteReceiptFile(userId, receipt.storedFilename)
        }
    }

    await Receipt.deleteMany({ userId }, BYPASS_SOFT_DELETE)
    return receiptIds
}

/**
 * Notifies the members who remain in each retained workspace that someone left and some records
 * are now unattributed (Part 2). Deliberately never names the departing user - they exercised a
 * deletion right, and re-introducing their identity into other people's data would undermine the
 * point of severing it in the first place.
 */
const notifyRemainingMembersOfDeparture = async (
    retainedWorkspaces: IWorkspace[],
    departingUserId: string
): Promise<void> => {
    for (const workspace of retainedWorkspaces) {
        const remainingMembers = workspace.members.filter(
            (member) => member.userId.toString() !== departingUserId
        )

        for (const member of remainingMembers) {
            await createNotificationIfNew({
                userId: member.userId.toString(),
                type: 'workspace_member_left',
                title: 'A member left your workspace',
                message: `A member left "${workspace.name}". Their contributions stay in the workspace but are no longer linked to them.`,
                referenceType: 'workspace',
                referenceId: workspace._id,
                // Includes the departing user's id (server-internal only - dedupeKey is never
                // serialized to the client, see notificationUtils.serializeNotification) so a
                // repeat notification can never double-fire for the same departure, mirroring
                // the workspace_invite dedupeKey convention in workspaceInviteUtils.ts.
                dedupeKey: `workspace_member_left:${workspace._id.toString()}:${departingUserId}`,
                metadata: {
                    workspaceId: workspace._id.toString(),
                    workspaceName: workspace.name,
                },
            })
        }
    }
}

/**
 * Hard-erases every resource this user owns individually - a genuine GDPR-style deletion,
 * distinct from the sync layer's `deletedAt` tombstones used for multi-device propagation.
 * Shared master categories (`userId: null`) are untouched.
 *
 * Workspace-capable resources (`WORKSPACE_CAPABLE_MODELS`) are no longer blanket-deleted by
 * `userId` alone - a record this user created inside a *shared* workspace belongs to that
 * workspace's other members too, not just to them:
 *
 *   - `workspaceId: null` (personal) records are hard-deleted exactly as before.
 *   - Records in a workspace that still has other members after this user leaves are RETAINED,
 *     with `userId` rewritten to `REMOVED_MEMBER_USER_ID` and `createdByRemovedUser: true` set -
 *     the record stops being this person's personal data without disappearing on their
 *     workspace-mates or being misattributed to one of them.
 *   - Every record in a workspace that has nobody left after this user leaves is hard-deleted
 *     regardless of who created it (that workspace, and its data, is now unreachable by anyone),
 *     and the workspace document itself is removed rather than left as an orphaned shell.
 *
 * `assertAccountDeletionAllowed` guards the one case this can't resolve on its own: being the
 * sole *owner* of a workspace that still has other members (ownership must be transferred first).
 */
export const deleteUserAccountCascade = async (userId: string): Promise<void> => {
    const { retainedWorkspaceIds, emptiedWorkspaceIds, retainedWorkspaces } =
        await computeWorkspaceDepartureImpact(userId)

    const deletedReceiptIds = await deleteUserReceipts(userId)

    // Receipts have no `workspaceId` of their own (always personal to the uploader), but a
    // receipt can be attached to a transaction the uploader doesn't own - e.g. a workspace-mate
    // attaches it to their own transaction. That means clearing the now-dangling reference can't
    // be expressed as a userId/workspaceId-scoped filter, so it needs RLS_BYPASS: this is a
    // single system-internal cleanup step inside account deletion (not a user-facing query), and
    // its only effect is pulling dead ids out of an array - it neither reads nor exposes anything.
    if (deletedReceiptIds.length > 0) {
        await Transaction.updateMany(
            { receiptIds: { $in: deletedReceiptIds } },
            { $pull: { receiptIds: { $in: deletedReceiptIds } } }
        ).setOptions({ [RLS_BYPASS]: true, ...BYPASS_SOFT_DELETE })
    }

    for (const { model, softDelete } of WORKSPACE_CAPABLE_MODELS) {
        const bypassOptions = softDelete ? BYPASS_SOFT_DELETE : {}

        // Personal records are this user's alone - hard-delete unchanged.
        await model.deleteMany({ userId, workspaceId: null }, bypassOptions)

        // Retain-and-anonymise this user's records in workspaces that still have other members.
        if (retainedWorkspaceIds.length > 0) {
            await model.updateMany(
                { userId, workspaceId: { $in: retainedWorkspaceIds } },
                { $set: { userId: REMOVED_MEMBER_USER_ID, createdByRemovedUser: true } },
                bypassOptions
            )
        }

        // Hard-delete everything (not just this user's rows) under a workspace nobody will be
        // left in - no orphans, regardless of who created what.
        if (emptiedWorkspaceIds.length > 0) {
            await model.deleteMany({ workspaceId: { $in: emptiedWorkspaceIds } }, bypassOptions)
        }
    }

    // A workspace this user was the last member of has nothing left to belong to.
    if (emptiedWorkspaceIds.length > 0) {
        await Workspace.deleteMany({ _id: { $in: emptiedWorkspaceIds } })
    }

    await Promise.all([
        Category.deleteMany({ userId }),
        SavingsGoalContribution.deleteMany({ userId }),
        Tag.deleteMany({ userId }, BYPASS_SOFT_DELETE),
        CategorizationRule.deleteMany({ userId }, BYPASS_SOFT_DELETE),
        TransactionTemplate.deleteMany({ userId }, BYPASS_SOFT_DELETE),
        Notification.deleteMany({ userId }, BYPASS_SOFT_DELETE),
        Saver.deleteMany({ userId }, BYPASS_SOFT_DELETE),
        Pushover.deleteMany({ userId }),
        Income.deleteMany({ userId }),
        Expense.deleteMany({ userId }),
    ])

    // Drop the now-deleted user from the member list of every workspace they're still in (the
    // retained ones - the emptied ones are already gone above).
    await Workspace.updateMany({ 'members.userId': userId }, { $pull: { members: { userId } } })

    await notifyRemainingMembersOfDeparture(retainedWorkspaces, userId)

    await revokeAllRefreshTokensForUser(userId)
    await User.deleteOne({ _id: userId })
}
