export const BASE_URL = import.meta.env.VITE_API_URL ?? 'http://localhost:5000/api/v1'

export const API_PATHS = {
    AUTH: {
        LOGIN: '/auth/login',
        REGISTER: '/auth/register',
        USER: '/auth/user',
        UPDATE_USER: '/auth/user',
        REFRESH: '/auth/refresh',
        LOGOUT: '/auth/logout',
        LOGOUT_ALL: '/auth/logout-all',
        PASSWORD_RESET_REQUEST: '/auth/password-reset/request',
        PASSWORD_RESET_CONFIRM: '/auth/password-reset/confirm',
    },
    INCOME: {
        CREATE: '/income/create',
        DOWNLOAD: '/income/download',
        GET_ALL: '/income',
        FILTER: '/income/filter',
        GROUP_BY_CATEGORY: '/income/group-by-category',
        SEARCH: '/income/search',
        DUPLICATE: (incomeId: string) => `/income/duplicate/${incomeId}`,
        GET_BY_ID: (incomeId: string) => `/income/${incomeId}`,
        DELETE: (incomeId: string) => `/income/${incomeId}`,
        UPDATE: (incomeId: string) => `/income/${incomeId}`,
    },
    EXPENSE: {
        CREATE: '/expense/create',
        GET_ALL: '/expense',
        GET_BY_ID: (expenseId: string) => `/expense/${expenseId}`,
        UPDATE: (expenseId: string) => `/expense/${expenseId}`,
        DELETE: (expenseId: string) => `/expense/${expenseId}`,
        FILTER: '/expense/filter',
        SEARCH: '/expense/search',
        GROUP_BY_CATEGORY: '/expense/group-by-category',
        GROUP_BY_PAYMENT_METHOD: '/expense/group-by-payment-method',
        DOWNLOAD: '/expense/download',
        REPORT: '/expense/report',
        DUPLICATE: (expenseId: string) => `/expense/duplicate/${expenseId}`,
    },
    SAVER: {
        ADD: '/saver/add',
        WITHDRAW: '/saver/withdraw',
        DETAILS: '/saver/details',
    },
    PUSHOVER: {
        PUSHOVER: '/pushover/pushover',
        HISTORY: '/pushover/history',
    },
    ACCOUNTS: {
        CREATE: '/accounts',
        GET_ALL: '/accounts',
        GET_BY_ID: (accountId: string) => `/accounts/${accountId}`,
        UPDATE: (accountId: string) => `/accounts/${accountId}`,
        DELETE: (accountId: string) => `/accounts/${accountId}`,
    },
    CATEGORIES: {
        CREATE: '/categories',
        GET_ALL: '/categories',
        GET_BY_ID: (categoryId: string) => `/categories/${categoryId}`,
        UPDATE: (categoryId: string) => `/categories/${categoryId}`,
        DELETE: (categoryId: string) => `/categories/${categoryId}`,
        REORDER: '/categories/reorder',
    },
    TAGS: {
        CREATE: '/tags',
        GET_ALL: '/tags',
        GET_BY_ID: (tagId: string) => `/tags/${tagId}`,
        UPDATE: (tagId: string) => `/tags/${tagId}`,
        DELETE: (tagId: string) => `/tags/${tagId}`,
        DEDUPE: '/tags/dedupe',
    },
    CATEGORIZATION_RULES: {
        CREATE: '/categorization-rules',
        GET_ALL: '/categorization-rules',
        GET_BY_ID: (ruleId: string) => `/categorization-rules/${ruleId}`,
        UPDATE: (ruleId: string) => `/categorization-rules/${ruleId}`,
        DELETE: (ruleId: string) => `/categorization-rules/${ruleId}`,
        BULK_APPLY: '/categorization-rules/bulk-apply',
        TEST: '/categorization-rules/test',
    },
    TRANSACTION_TEMPLATES: {
        CREATE: '/transaction-templates',
        GET_ALL: '/transaction-templates',
        GET_BY_ID: (templateId: string) => `/transaction-templates/${templateId}`,
        UPDATE: (templateId: string) => `/transaction-templates/${templateId}`,
        DELETE: (templateId: string) => `/transaction-templates/${templateId}`,
        APPLY: (templateId: string) => `/transaction-templates/${templateId}/apply`,
    },
    TRANSACTIONS: {
        CREATE: '/transactions',
        TRANSFER: '/transactions/transfer',
        BULK_DELETE: '/transactions/bulk/delete',
        BULK_CATEGORY: '/transactions/bulk/category',
        GET_ALL: '/transactions',
        GET_BY_ID: (transactionId: string) => `/transactions/${transactionId}`,
        UPDATE: (transactionId: string) => `/transactions/${transactionId}`,
        DELETE: (transactionId: string) => `/transactions/${transactionId}`,
        ATTACH_RECEIPT: (transactionId: string) => `/transactions/${transactionId}/receipts`,
        DETACH_RECEIPT: (transactionId: string, receiptId: string) =>
            `/transactions/${transactionId}/receipts/${receiptId}`,
        FILTER: '/transactions/filter',
        SEARCH: '/transactions/search',
        DOWNLOAD: '/transactions/download',
        DUPLICATE: (transactionId: string) => `/transactions/duplicate/${transactionId}`,
    },
    RECEIPTS: {
        UPLOAD: '/receipts',
        GET_FILE: (receiptId: string) => `/receipts/${receiptId}`,
        DELETE: (receiptId: string) => `/receipts/${receiptId}`,
    },
    BUDGETS: {
        CREATE: '/budgets',
        GET_ALL: '/budgets',
        GET_BY_ID: (budgetId: string) => `/budgets/${budgetId}`,
        UPDATE: (budgetId: string) => `/budgets/${budgetId}`,
        DELETE: (budgetId: string) => `/budgets/${budgetId}`,
        PROGRESS: (budgetId: string) => `/budgets/${budgetId}/progress`,
    },
    SAVINGS_GOALS: {
        CREATE: '/savings-goals',
        GET_ALL: '/savings-goals',
        GET_BY_ID: (goalId: string) => `/savings-goals/${goalId}`,
        UPDATE: (goalId: string) => `/savings-goals/${goalId}`,
        DELETE: (goalId: string) => `/savings-goals/${goalId}`,
        PROGRESS: (goalId: string) => `/savings-goals/${goalId}/progress`,
        CONTRIBUTE: (goalId: string) => `/savings-goals/${goalId}/contribute`,
        AUTO_CONTRIBUTE: (goalId: string) => `/savings-goals/${goalId}/auto-contribute`,
        CONTRIBUTIONS: (goalId: string) => `/savings-goals/${goalId}/contributions`,
        PAUSE: (goalId: string) => `/savings-goals/${goalId}/pause`,
        RESUME: (goalId: string) => `/savings-goals/${goalId}/resume`,
        COMPLETE: (goalId: string) => `/savings-goals/${goalId}/complete`,
    },
    RECURRING_RULES: {
        CREATE: '/recurring-rules',
        GET_ALL: '/recurring-rules',
        GET_BY_ID: (ruleId: string) => `/recurring-rules/${ruleId}`,
        UPDATE: (ruleId: string) => `/recurring-rules/${ruleId}`,
        DELETE: (ruleId: string) => `/recurring-rules/${ruleId}`,
        GENERATE_DRAFTS: '/recurring-rules/generate-drafts',
        GENERATE_DRAFTS_FOR_RULE: (ruleId: string) => `/recurring-rules/${ruleId}/generate-drafts`,
        GET_DRAFTS: '/recurring-rules/drafts',
        CONFIRM_DRAFT: (transactionId: string) =>
            `/recurring-rules/drafts/${transactionId}/confirm`,
        DISMISS_DRAFT: (transactionId: string) =>
            `/recurring-rules/drafts/${transactionId}/dismiss`,
    },
    DASHBOARD: {
        SUMMARY: '/dashboard/summary',
        CASH_FLOW: '/dashboard/cash-flow',
        CATEGORY_BREAKDOWN: '/dashboard/category-breakdown',
        NET_WORTH_TREND: '/dashboard/net-worth-trend',
        BUDGET_OVERVIEW: '/dashboard/budget-overview',
    },
    REPORTS: {
        AVERAGES: '/dashboard/reports/averages',
        LARGEST_EXPENSES: '/dashboard/reports/largest-expenses',
        SPENDING_TRENDS: '/dashboard/reports/spending-trends',
        INCOME_VS_EXPENSE: '/dashboard/reports/income-vs-expense',
        SAVINGS_RATE: '/dashboard/reports/savings-rate',
        RECURRING_TOTALS: '/dashboard/reports/recurring-totals',
        BUDGET_ANALYSIS: '/dashboard/reports/budget-analysis',
        SPENDING_ANALYSIS: '/dashboard/reports/spending-analysis',
        CROSSOVER_POINT: '/dashboard/reports/crossover-point',
        QUERY: '/dashboard/reports/query',
        GENERATE: '/dashboard/reports/generate',
        SAVED: '/dashboard/reports/saved',
        SAVED_RUN: (reportId: string) => `/dashboard/reports/saved/${reportId}/run`,
    },
    NOTIFICATIONS: {
        GET_ALL: '/notifications',
        MARK_READ: (notificationId: string) => `/notifications/${notificationId}/read`,
        DISMISS: (notificationId: string) => `/notifications/${notificationId}/dismiss`,
        MARK_ALL_READ: '/notifications/read-all',
    },
    WORKSPACES: {
        CREATE: '/workspaces',
        GET_ALL: '/workspaces',
        GET_BY_ID: (workspaceId: string) => `/workspaces/${workspaceId}`,
        UPDATE: (workspaceId: string) => `/workspaces/${workspaceId}`,
        INVITE: (workspaceId: string) => `/workspaces/${workspaceId}/members`,
        PENDING_INVITES: (workspaceId: string) => `/workspaces/${workspaceId}/invites`,
        RECEIVED_INVITES: '/workspaces/invites/received',
        ACCEPT_INVITE: (inviteId: string) => `/workspaces/invites/${inviteId}/accept`,
        DECLINE_INVITE: (inviteId: string) => `/workspaces/invites/${inviteId}/decline`,
        UPDATE_MEMBER: (workspaceId: string, memberUserId: string) =>
            `/workspaces/${workspaceId}/members/${memberUserId}`,
        REMOVE_MEMBER: (workspaceId: string, memberUserId: string) =>
            `/workspaces/${workspaceId}/members/${memberUserId}`,
    },
    IMPORTS: {
        PARSE: '/imports/parse',
        PREVIEW: '/imports/preview',
        COMMIT: '/imports/commit',
    },
} as const
